---
title: "counties_new_Processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("../output/counties.RData")
Edu <-c("% of adults with less than a high school diploma", 
        "% of adults with a high school diploma only", 
        "% of adults completing some college",
        "% of adults with a bachelor's degree or higher")
Popu <- c("Population",
          "Natural population increase rate", 
          "Birth rate", 
          "Death rate",
          "Net migration rate")
Emplo <- c("Civilian Labor Force", 
           "Unemployment Rate")
Pover <- c("Median Household Income", 
           "% of people age 0-17 in poverty",
           "% of people in poverty")

df<-counties %>% mutate(base_metric = "NA")

df = df %>% mutate(base_metric = ifelse(Metric %in% Edu, "Education", base_metric)) %>%
  mutate(base_metric = ifelse(Metric %in% Popu, "Population", base_metric)) %>%
  mutate(base_metric = ifelse(Metric %in% Emplo, "Employment", base_metric)) %>%
  mutate(base_metric = ifelse(Metric %in% Pover, "Poverty", base_metric)) 

df_name = df %>% select(State) %>% unique() %>% c() %>% with(State)
df_name = tibble(abb = df_name)
abb_name = tibble(abb = state.abb, name = state.name)
df_join = full_join(df_name, abb_name, by = 'abb')
df_join[9,2] = 'Washington D.C.'
df_join[52,2] = 'Puerto Rico'

df = left_join(df, df_join, by = c('State' = 'abb')) %>% 
  select(FIPS, State = name, Name, Metric, Year, Value, base_metric)

counties_new <- df %>% mutate(Value = signif(Value, 5))
save(counties_new, file="../app/counties_new.RData")
```

