---
title: "Economic Data Processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(readxl)
```

```{r}
education <- read_xls('../data/Education.xls', skip=4) %>%
  select(`FIPS` = `FIPS Code`,
  `State` = `State`,
  `Name` = `Area name`,
  `% of adults with less than a high school diploma/1970` = `Percent of adults with less than a high school diploma, 1970`,
  `% of adults with a high school diploma only/1970` = `Percent of adults with a high school diploma only, 1970`,
  `% of adults completing some college/1970` = `Percent of adults completing some college (1-3 years), 1970`,
  `% of adults with a bachelor's degree or higher/1970` = `Percent of adults completing four years of college or higher, 1970`,
  `% of adults with less than a high school diploma/1980` = `Percent of adults with less than a high school diploma, 1980`,
  `% of adults with a high school diploma only/1980` = `Percent of adults with a high school diploma only, 1980`,
  `% of adults completing some college/1980` = `Percent of adults completing some college (1-3 years), 1980`,
  `% of adults with a bachelor's degree or higher/1980` = `Percent of adults completing four years of college or higher, 1980`,
  `% of adults with less than a high school diploma/1990` = `Percent of adults with less than a high school diploma, 1990`,
  `% of adults with a high school diploma only/1990` = `Percent of adults with a high school diploma only, 1990`,
  `% of adults completing some college/1990` = `Percent of adults completing some college or associate's degree, 1990`,
  `% of adults with a bachelor's degree or higher/1990` = `Percent of adults with a bachelor's degree or higher, 1990`,
  `% of adults with less than a high school diploma/2000` = `Percent of adults with less than a high school diploma, 2000`,
  `% of adults with a high school diploma only/2000` = `Percent of adults with a high school diploma only, 2000`,
  `% of adults completing some college/2000` = `Percent of adults completing some college or associate's degree, 2000`,
  `% of adults with a bachelor's degree or higher/2000` = `Percent of adults with a bachelor's degree or higher, 2000`,
  `% of adults with less than a high school diploma/2014-18` = `Percent of adults with less than a high school diploma, 2014-18`,
  `% of adults with a high school diploma only/2014-18` = `Percent of adults with a high school diploma only, 2014-18`,
  `% of adults completing some college/2014-18` = `Percent of adults completing some college or associate's degree, 2014-18`,
  `% of adults with a bachelor's degree or higher/2014-18` = `Percent of adults with a bachelor's degree or higher, 2014-18`)
unemployment <- read_xls('../data/Unemployment.xls', skip=4) %>%
  select(`FIPS` = `FIPS`,
  `Civilian Labor Force/2007` = `Civilian_labor_force_2007`,
  `Employed/2007` = `Employed_2007`,
  `Unemployed/2007` = `Unemployed_2007`,
  `Unemployment Rate/2007` = `Unemployment_rate_2007`,
  `Civilian Labor Force/2008` = `Civilian_labor_force_2008`,
  `Employed/2008` = `Employed_2008`,
  `Unemployed/2008` = `Unemployed_2008`,
  `Unemployment Rate/2008` = `Unemployment_rate_2008`,
  `Civilian Labor Force/2009` = `Civilian_labor_force_2009`,
  `Employed/2009` = `Employed_2009`,
  `Unemployed/2009` = `Unemployed_2009`,
  `Unemployment Rate/2009` = `Unemployment_rate_2009`,
  `Civilian Labor Force/2010` = `Civilian_labor_force_2010`,
  `Employed/2010` = `Employed_2010`,
  `Unemployed/2010` = `Unemployed_2010`,
  `Unemployment Rate/2010` = `Unemployment_rate_2010`,
  `Civilian Labor Force/2011` = `Civilian_labor_force_2011`,
  `Employed/2011` = `Employed_2011`,
  `Unemployed/2011` = `Unemployed_2011`,
  `Unemployment Rate/2011` = `Unemployment_rate_2011`,
  `Civilian Labor Force/2012` = `Civilian_labor_force_2012`,
  `Employed/2012` = `Employed_2012`,
  `Unemployed/2012` = `Unemployed_2012`,
  `Unemployment Rate/2012` = `Unemployment_rate_2012`,
  `Civilian Labor Force/2013` = `Civilian_labor_force_2013`,
  `Employed/2013` = `Employed_2013`,
  `Unemployed/2013` = `Unemployed_2013`,
  `Unemployment Rate/2013` = `Unemployment_rate_2013`,
  `Civilian Labor Force/2014` = `Civilian_labor_force_2014`,
  `Employed/2014` = `Employed_2014`,
  `Unemployed/2014` = `Unemployed_2014`,
  `Unemployment Rate/2014` = `Unemployment_rate_2014`,
  `Civilian Labor Force/2015` = `Civilian_labor_force_2015`,
  `Employed/2015` = `Employed_2015`,
  `Unemployed/2015` = `Unemployed_2015`,
  `Unemployment Rate/2015` = `Unemployment_rate_2015`,
  `Civilian Labor Force/2016` = `Civilian_labor_force_2016`,
  `Employed/2016` = `Employed_2016`,
  `Unemployed/2016` = `Unemployed_2016`,
  `Unemployment Rate/2016` = `Unemployment_rate_2016`,
  `Civilian Labor Force/2017` = `Civilian_labor_force_2017`,
  `Employed/2017` = `Employed_2017`,
  `Unemployed/2017` = `Unemployed_2017`,
  `Unemployment Rate/2017` = `Unemployment_rate_2017`,
  `Civilian Labor Force/2018` = `Civilian_labor_force_2018`,
  `Employed/2018` = `Employed_2018`,
  `Unemployed/2018` = `Unemployed_2018`,
  `Unemployment Rate/2018` = `Unemployment_rate_2018`)
poverty <- read_xls('../data/PovertyEstimates.xls', skip=4) %>%
  select(`FIPS` = `FIPStxt`,
  `% of people in poverty/2018` = `PCTPOVALL_2018`,
  `% of people age 0-17 in poverty/2018` = `PCTPOV017_2018`,
  `% of people age 5-17 in poverty/2018` = `PCTPOV517_2018`,
  `Median Household Income/2018` = `MEDHHINC_2018`,
  `% of people age 0-4 in poverty/2018` = `PCTPOV04_2018`)
population <- read_xls('../data/PopulationEstimates.xls', skip=2) %>%
  select(`FIPS` = `FIPS`,
  `Population/2010` = `POP_ESTIMATE_2010`,
  `Population/2011` = `POP_ESTIMATE_2011`,
  `Population/2012` = `POP_ESTIMATE_2012`,
  `Population/2013` = `POP_ESTIMATE_2013`,
  `Population/2014` = `POP_ESTIMATE_2014`,
  `Population/2015` = `POP_ESTIMATE_2015`,
  `Population/2016` = `POP_ESTIMATE_2016`,
  `Population/2017` = `POP_ESTIMATE_2017`,
  `Population/2018` = `POP_ESTIMATE_2018`,
  `Change in population/2011` = `N_POP_CHG_2011`,
  `Change in population/2012` = `N_POP_CHG_2012`,
  `Change in population/2013` = `N_POP_CHG_2013`,
  `Change in population/2014` = `N_POP_CHG_2014`,
  `Change in population/2015` = `N_POP_CHG_2015`,
  `Change in population/2016` = `N_POP_CHG_2016`,
  `Change in population/2017` = `N_POP_CHG_2017`,
  `Change in population/2018` = `N_POP_CHG_2018`,
  `Births/2011` = `Births_2011`,
  `Births/2012` = `Births_2012`,
  `Births/2013` = `Births_2013`,
  `Births/2014` = `Births_2014`,
  `Births/2015` = `Births_2015`,
  `Births/2016` = `Births_2016`,
  `Births/2017` = `Births_2017`,
  `Births/2018` = `Births_2018`,
  `Deaths/2011` = `Deaths_2011`,
  `Deaths/2012` = `Deaths_2012`,
  `Deaths/2013` = `Deaths_2013`,
  `Deaths/2014` = `Deaths_2014`,
  `Deaths/2015` = `Deaths_2015`,
  `Deaths/2016` = `Deaths_2016`,
  `Deaths/2017` = `Deaths_2017`,
  `Deaths/2018` = `Deaths_2018`,
  `Natural population increase/2011` = `NATURAL_INC_2011`,
  `Natural population increase/2012` = `NATURAL_INC_2012`,
  `Natural population increase/2013` = `NATURAL_INC_2013`,
  `Natural population increase/2014` = `NATURAL_INC_2014`,
  `Natural population increase/2015` = `NATURAL_INC_2015`,
  `Natural population increase/2016` = `NATURAL_INC_2016`,
  `Natural population increase/2017` = `NATURAL_INC_2017`,
  `Natural population increase/2018` = `NATURAL_INC_2018`,
  `Net international migration/2011` = `INTERNATIONAL_MIG_2011`,
  `Net international migration/2012` = `INTERNATIONAL_MIG_2012`,
  `Net international migration/2013` = `INTERNATIONAL_MIG_2013`,
  `Net international migration/2014` = `INTERNATIONAL_MIG_2014`,
  `Net international migration/2015` = `INTERNATIONAL_MIG_2015`,
  `Net international migration/2016` = `INTERNATIONAL_MIG_2016`,
  `Net international migration/2017` = `INTERNATIONAL_MIG_2017`,
  `Net international migration/2018` = `INTERNATIONAL_MIG_2018`,
  `Net domestic migration/2011` = `DOMESTIC_MIG_2011`,
  `Net domestic migration/2012` = `DOMESTIC_MIG_2012`,
  `Net domestic migration/2013` = `DOMESTIC_MIG_2013`,
  `Net domestic migration/2014` = `DOMESTIC_MIG_2014`,
  `Net domestic migration/2015` = `DOMESTIC_MIG_2015`,
  `Net domestic migration/2016` = `DOMESTIC_MIG_2016`,
  `Net domestic migration/2017` = `DOMESTIC_MIG_2017`,
  `Net domestic migration/2018` = `DOMESTIC_MIG_2018`,
  `Net migration/2011` = `NET_MIG_2011`,
  `Net migration/2012` = `NET_MIG_2012`,
  `Net migration/2013` = `NET_MIG_2013`,
  `Net migration/2014` = `NET_MIG_2014`,
  `Net migration/2015` = `NET_MIG_2015`,
  `Net migration/2016` = `NET_MIG_2016`,
  `Net migration/2017` = `NET_MIG_2017`,
  `Net migration/2018` = `NET_MIG_2018`,
  `Group Quarters total population/2010` = `GQ_ESTIMATES_2010`,
  `Group Quarters total population/2011` = `GQ_ESTIMATES_2011`,
  `Group Quarters total population/2012` = `GQ_ESTIMATES_2012`,
  `Group Quarters total population/2013` = `GQ_ESTIMATES_2013`,
  `Group Quarters total population/2014` = `GQ_ESTIMATES_2014`,
  `Group Quarters total population/2015` = `GQ_ESTIMATES_2015`,
  `Group Quarters total population/2016` = `GQ_ESTIMATES_2016`,
  `Group Quarters total population/2017` = `GQ_ESTIMATES_2017`,
  `Group Quarters total population/2018` = `GQ_ESTIMATES_2018`,
  `Birth rate/2011` = `R_birth_2011`,
  `Birth rate/2012` = `R_birth_2012`,
  `Birth rate/2013` = `R_birth_2013`,
  `Birth rate/2014` = `R_birth_2014`,
  `Birth rate/2015` = `R_birth_2015`,
  `Birth rate/2016` = `R_birth_2016`,
  `Birth rate/2017` = `R_birth_2017`,
  `Birth rate/2018` = `R_birth_2018`,
  `Death rate/2011` = `R_death_2011`,
  `Death rate/2012` = `R_death_2012`,
  `Death rate/2013` = `R_death_2013`,
  `Death rate/2014` = `R_death_2014`,
  `Death rate/2015` = `R_death_2015`,
  `Death rate/2016` = `R_death_2016`,
  `Death rate/2017` = `R_death_2017`,
  `Death rate/2018` = `R_death_2018`,
  `Natural population increase rate/2011` = `R_NATURAL_INC_2011`,
  `Natural population increase rate/2012` = `R_NATURAL_INC_2012`,
  `Natural population increase rate/2013` = `R_NATURAL_INC_2013`,
  `Natural population increase rate/2014` = `R_NATURAL_INC_2014`,
  `Natural population increase rate/2015` = `R_NATURAL_INC_2015`,
  `Natural population increase rate/2016` = `R_NATURAL_INC_2016`,
  `Natural population increase rate/2017` = `R_NATURAL_INC_2017`,
  `Natural population increase rate/2018` = `R_NATURAL_INC_2018`,
  `Net international migration rate/2011` = `R_INTERNATIONAL_MIG_2011`,
  `Net international migration rate/2012` = `R_INTERNATIONAL_MIG_2012`,
  `Net international migration rate/2013` = `R_INTERNATIONAL_MIG_2013`,
  `Net international migration rate/2014` = `R_INTERNATIONAL_MIG_2014`,
  `Net international migration rate/2015` = `R_INTERNATIONAL_MIG_2015`,
  `Net international migration rate/2016` = `R_INTERNATIONAL_MIG_2016`,
  `Net international migration rate/2017` = `R_INTERNATIONAL_MIG_2017`,
  `Net international migration rate/2018` = `R_INTERNATIONAL_MIG_2018`,
  `Net domestic migration rate/2011` = `R_DOMESTIC_MIG_2011`,
  `Net domestic migration rate/2012` = `R_DOMESTIC_MIG_2012`,
  `Net domestic migration rate/2013` = `R_DOMESTIC_MIG_2013`,
  `Net domestic migration rate/2014` = `R_DOMESTIC_MIG_2014`,
  `Net domestic migration rate/2015` = `R_DOMESTIC_MIG_2015`,
  `Net domestic migration rate/2016` = `R_DOMESTIC_MIG_2016`,
  `Net domestic migration rate/2017` = `R_DOMESTIC_MIG_2017`,
  `Net domestic migration rate/2018` = `R_DOMESTIC_MIG_2018`,
  `Net migration rate/2011` = `R_NET_MIG_2011`,
  `Net migration rate/2012` = `R_NET_MIG_2012`,
  `Net migration rate/2013` = `R_NET_MIG_2013`,
  `Net migration rate/2014` = `R_NET_MIG_2014`,
  `Net migration rate/2015` = `R_NET_MIG_2015`,
  `Net migration rate/2016` = `R_NET_MIG_2016`,
  `Net migration rate/2017` = `R_NET_MIG_2017`,
  `Net migration rate/2018` = `R_NET_MIG_2018`)
```

```{r}
full_data <- education %>%
  merge(unemployment, by='FIPS', all.x=TRUE, all.y=TRUE) %>%
  merge(poverty, by='FIPS', all.x=TRUE, all.y=TRUE) %>%
  merge(population, by='FIPS', all.x=TRUE, all.y=TRUE)
states <- full_data %>% filter(endsWith(FIPS, "000") & FIPS!="00000") %>%
  pivot_longer(cols=-c('FIPS','State','Name'), names_to='Observation', values_to='Value') %>%
  separate(Observation, c('Metric','Year'), sep='/')
counties <- full_data %>% filter(!endsWith(FIPS, "000")) %>%
  pivot_longer(cols=-c('FIPS','State','Name'), names_to='Observation', values_to='Value') %>%
  separate(Observation, c('Metric','Year'), sep='/')
```

```{r}
save(states, file="../output/states.RData")
save(counties, file="../output/counties.RData")
```
