---
title: "park_analysis"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r include=FALSE,message=FALSE}
library(tidyverse)
library(tidyr)
library(dplyr)
load("~/Documents/GitHub/Spring2020-Project2-group7/output/park.RData")
load("~/Documents/GitHub/Spring2020-Project2-group7/output/park_event.RData")
load("~/Documents/GitHub/Spring2020-Project2-group7/output/park_crime.RData")
park<-as_tibble(PARK)%>%drop_na()
park_event<-as_tibble(park_event)%>%drop_na()
park_crime<-as_tibble(park_crime)%>%drop_na()
```


```{r pressure}
p<-park_event%>%inner_join(park,by=c("park_id"="PARKNUM"))
event<-p%>%group_by(PARK_NAME)%>%count(event_name)
listing<-event%>%group_by(PARK_NAME)%>%summarize(cnt=sum(n))
listing
```
```{r,fig.height=30,fig.width=4}
ggplot(listing,aes(PARK_NAME,cnt)) + geom_bar(stat="identity") +coord_flip()

```

```{r}
park$PARK_NAME<-tolower(park$PARK_NAME)
park_crime$PARK<-tolower(park_crime$PARK)
crime<-park%>%inner_join(park_crime,by=c("PARK_NAME"="PARK"))
crime_2015<-crime%>%group_by(PARK_NAME)%>%filter(Year=="2015")%>%mutate(cnt=sum(MURDER+RAPE+ROBBERY+GRAND.LARCENY+GRAND.LARCENY.OF.MOTOR.VEHICLE+FELONY.ASSAULT+BURGLARY))%>%select(PARK_NAME,cnt)%>%unique()
crime_2016<-crime%>%group_by(PARK_NAME)%>%filter(Year=="2016")%>%mutate(cnt=sum(MURDER+RAPE+ROBBERY+GRAND.LARCENY+GRAND.LARCENY.OF.MOTOR.VEHICLE+FELONY.ASSAULT+BURGLARY))%>%select(PARK_NAME,cnt)%>%unique()
crime_2017<-crime%>%group_by(PARK_NAME)%>%filter(Year=="2017")%>%mutate(cnt=sum(MURDER+RAPE+ROBBERY+GRAND.LARCENY+GRAND.LARCENY.OF.MOTOR.VEHICLE+FELONY.ASSAULT+BURGLARY))%>%select(PARK_NAME,cnt)%>%unique()
crime_2018<-crime%>%group_by(PARK_NAME)%>%filter(Year=="2018")%>%mutate(cnt=sum(MURDER+RAPE+ROBBERY+GRAND.LARCENY+GRAND.LARCENY.OF.MOTOR.VEHICLE+FELONY.ASSAULT+BURGLARY))%>%select(PARK_NAME,cnt)%>%unique()
crime_2019<-crime%>%group_by(PARK_NAME)%>%filter(Year=="2019")%>%mutate(cnt=sum(MURDER+RAPE+ROBBERY+GRAND.LARCENY+GRAND.LARCENY.OF.MOTOR.VEHICLE+FELONY.ASSAULT+BURGLARY))%>%select(PARK_NAME,cnt)%>%unique()
crime_2015
crime_2016
crime_2017
crime_2018
crime_2019
```

```{r,fig.height=18,fig.width=4}
#ggplot(crime_2015%>%filter(cnt<=100&cnt!=0),aes(PARK_NAME,cnt)) + geom_bar(stat="identity") +coord_flip()
ggplot(crime_2015%>%filter(cnt!=0),aes(PARK_NAME,cnt)) + geom_bar(stat="identity") +coord_flip()
```

```{r,fig.width=4,fig.height=18}
ggplot(crime_2016%>%filter(cnt!=0),aes(PARK_NAME,cnt)) + geom_bar(stat="identity") +coord_flip()
```

```{r,fig.width=4,fig.height=18}
ggplot(crime_2017%>%filter(cnt!=0),aes(PARK_NAME,cnt)) + geom_bar(stat="identity") +coord_flip()
```

```{r,fig.width=4,fig.height=18}
ggplot(crime_2018%>%filter(cnt!=0),aes(PARK_NAME,cnt)) + geom_bar(stat="identity") +coord_flip()
```

```{r,fig.width=4,fig.height=18}
ggplot(crime_2019%>%filter(cnt!=0),aes(PARK_NAME,cnt)) + geom_bar(stat="identity") +coord_flip()
```

