library(tidyverse)
library(ggplot2)
library(plotly)
load("~/Documents/GitHub/Spring2020-Project2-group7/output/Econ_county_map.Rdata")
index1<-function(df){
  df[,3]%>%unlist()
}
index2<-function(df){
  df[,4]%>%unlist()
}
index<-function(df){
  df%>%select(-Name,-Year,-State)%>%unlist()
}
